# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WeatherForecast' do

    pod 'ReachabilitySwift'
    pod 'PKHUD'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Alamofire', '~> 3.3.1'
    pod 'IQKeyboardManagerSwift'

end

