# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'WeatherForecast' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherForecast

    pod 'ReachabilitySwift'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Alamofire', '~> 3.3.1'
    pod 'IQKeyboardManagerSwift'
    pod 'SDWebImage'

end
